sudo rm -r front-end/node_modules && echo "node_modules removed"
sudo rm -r front-end/certbot && echo "certbot removed"
sudo rm -r front-end/nginx/logs && echo "logs removed"
sudo rm -r front-end/.parcel-cache && echo "parcel-cache removed"
sudo rm -r front-end/dist && echo "dist removed"