#!/bin/bash

if [[ "$1" = "-s" ]]
then
    ./scripts/dev-start.sh
    exit
fi

if [[ "$1" = "-d" ]]
then
    ./scripts/dev-stop.sh
    exit
fi

if [[ "$1" = "-c" ]]
then
    ./scripts/clean.sh
    exit
fi

text="dev containers"

echo "Enter -s for start $text"
echo "Enter -d for stop $text"
echo "Enter -c for clean $text"