version: "3.9"

services:
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./front-end/nginx/logs/:/var/log/nginx/:rw
      - ./front-end/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./front-end/dist/:/usr/share/nginx/html/:ro
      - /var/www/html/:/var/www/html/:ro
