version: "3.9"

services:
  reverse-proxy:
    image: nginx:1.21.6-alpine
    container_name: reverse-proxy
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/logs/:/var/log/nginx/:rw
      - ./reverse-proxy/conf.d/:/etc/nginx/conf.d/:ro
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - /etc/ssl/dhparamcerts.pem:/etc/ssl/dhparamcerts.pem:ro
      - /var/www/html/:/var/www/html/:ro

  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    container_name: web
    volumes:
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  dashboard:
    build:
      context: ./react-dashboard
      dockerfile: Dockerfile.prod
    container_name: dashboard
    depends_on:
      - api
    volumes:
      - ./react-dashboard/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile.prod
    container_name: api
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://data-base/my-site
    pid: "host"

  db:
    image: mongo:4.4.14-focal
    container_name: data-base
    ports:
      - 27017:27017
    volumes:
      - ./data-base:/data/db # for testing
      # - /mnt/external/mongodb:/data/db # for production
