version: "3.9"

services:
  reverse-proxy:
    image: nginx:1.21.6-alpine
    container_name: reverse-proxy
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy/conf.d/:/etc/nginx/conf.d/:ro
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/logs/:/var/log/nginx/:rw
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front-end/dist/:/usr/share/nginx/html/:ro
      - /var/www/html/:/var/www/html/:ro
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    pid: "host"
