version: "3.9"

services:
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    container_name: web
    depends_on:
      - api
    ports:
      - 80:1234
    volumes:
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front-end/dist/:/usr/share/nginx/html/:ro
      - ./front-end/:/app/

  dashboard:
    build:
      context: ./react-dashboard
      dockerfile: Dockerfile.dev
    container_name: dashboard
    depends_on:
      - api
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://192.168.1.137:3001
    volumes:
      - ./react-dashboard/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./react-dashboard/build/:/usr/share/nginx/html/:ro
      - ./react-dashboard/:/app/

  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    container_name: api
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - DB_URL=mongodb://data-base/my-site
      - WORKERS=1
    pid: "host"
    volumes:
      - ./back-end/:/app/

  db:
    image: mongo:4.4.14-focal
    container_name: data-base
    ports:
      - 27017:27017
    volumes:
      - ./data-base:/data/db
