version: "3.9"

services:
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./front-end/nginx/logs/:/var/log/nginx/:rw
      - ./front-end/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./front-end/certbot/www:/var/www/certbot/:ro
      # - ./front-end/certbot/conf/:/etc/nginx/ssl/
