version: "3.9"

services:
  reverse-proxy:
    image: nginx:1.21.6-alpine
    container_name: reverse-proxy
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/logs/:/var/log/nginx/:rw
      - ./reverse-proxy/conf.d/:/etc/nginx/conf.d/:ro
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - /etc/ssl/dhparamcerts.pem:/etc/ssl/dhparamcerts.pem:ro
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    container_name: web
    volumes:
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/html/:/var/www/html/:ro
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: api
    pid: "host"
