FROM node:16-bullseye AS build

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://192.168.1.137/api
RUN npm run build

FROM nginx:1.21.6-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx","-g","daemon off;" ]